services:
  mysql:
    image: mysql:latest
    container_name: jobsy-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: jobsy_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mailpit:
    image: axllent/mailpit:latest
    container_name: jobsy_mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - mailpit_data:/data

volumes:
  mysql_data:
  mailpit_data: